In [265]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler
ds=pd.read_csv("C:/Users/jaswa/Downloads/lifestyle_and_wellbeing/Wellbeing_and_lifestyle_data_Kaggle.csv")
ds.head()

,Timestamp,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,7/7/15,3,2,2,5,0,5,2,0,1,...,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,7/7/15,2,3,4,3,8,10,5,2,2,...,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,7/7/15,2,3,3,4,4,10,3,2,2,...,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,7/7/15,3,3,10,3,10,7,2,5,2,...,5,7,5,1,5,2,0,51 or more,Female,622.7
4,7/7/15,5,1,3,3,10,4,2,4,2,...,7,0,0,2,8,1,5,51 or more,Female,663.9

In [266]:
ds.shape
ds.dtypes

Timestamp                   object
FRUITS_VEGGIES               int64
DAILY_STRESS                object
PLACES_VISITED               int64
CORE_CIRCLE                  int64
SUPPORTING_OTHERS            int64
SOCIAL_NETWORK               int64
ACHIEVEMENT                  int64
DONATION                     int64
BMI_RANGE                    int64
TODO_COMPLETED               int64
FLOW                         int64
DAILY_STEPS                  int64
LIVE_VISION                  int64
SLEEP_HOURS                  int64
LOST_VACATION                int64
DAILY_SHOUTING               int64
SUFFICIENT_INCOME            int64
PERSONAL_AWARDS              int64
TIME_FOR_PASSION             int64
WEEKLY_MEDITATION            int64
AGE                         object
GENDER                      object
WORK_LIFE_BALANCE_SCORE    float64
dtype: object

In [267]:
ds['DAILY_STRESS'] = pd.to_datetime(ds['DAILY_STRESS'], errors='coerce')
ds['DAILY_STRESS'] = pd.to_numeric(ds['DAILY_STRESS'], errors='coerce')




ds['DAILY_STRESS'] = ds['DAILY_STRESS'].astype(int)

In [268]:
ds.dtypes

Timestamp                   object
FRUITS_VEGGIES               int64
DAILY_STRESS                 int32
PLACES_VISITED               int64
CORE_CIRCLE                  int64
SUPPORTING_OTHERS            int64
SOCIAL_NETWORK               int64
ACHIEVEMENT                  int64
DONATION                     int64
BMI_RANGE                    int64
TODO_COMPLETED               int64
FLOW                         int64
DAILY_STEPS                  int64
LIVE_VISION                  int64
SLEEP_HOURS                  int64
LOST_VACATION                int64
DAILY_SHOUTING               int64
SUFFICIENT_INCOME            int64
PERSONAL_AWARDS              int64
TIME_FOR_PASSION             int64
WEEKLY_MEDITATION            int64
AGE                         object
GENDER                      object
WORK_LIFE_BALANCE_SCORE    float64
dtype: object

In [269]:
ds.describe()

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,WORK_LIFE_BALANCE_SCORE
count,15972.000000,1.597200e+04,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,...,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000
mean,2.922677,8.640888e+04,5.232970,5.508077,5.616454,6.474267,4.000751,2.715314,1.410656,5.745993,...,5.703606,3.752129,7.042888,2.898886,2.930879,1.728963,5.711558,3.326572,6.233346,666.751503
std,1.442694,1.092039e+07,3.311912,2.840334,3.242021,3.086672,2.755837,1.851586,0.491968,2.624097,...,2.891013,3.230987,1.199044,3.692180,2.676301,0.444509,3.089630,2.729293,3.016571,45.019868
min,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,480.000000
25%,2.000000,0.000000e+00,2.000000,3.000000,3.000000,4.000000,2.000000,1.000000,1.000000,4.000000,...,3.000000,1.000000,6.000000,0.000000,1.000000,1.000000,3.000000,1.000000,4.000000,636.000000
50%,3.000000,0.000000e+00,5.000000,5.000000,5.000000,6.000000,3.000000,3.000000,1.000000,6.000000,...,5.000000,3.000000,7.000000,0.000000,2.000000,2.000000,5.000000,3.000000,7.000000,667.700000
75%,4.000000,0.000000e+00,8.000000,8.000000,10.000000,10.000000,6.000000,5.000000,2.000000,8.000000,...,8.000000,5.000000,8.000000,5.000000,4.000000,2.000000,9.000000,5.000000,10.000000,698.500000
max,5.000000,1.380123e+09,10.000000,10.000000,10.000000,10.000000,10.000000,5.000000,2.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,10.000000,10.000000,10.000000,820.200000

In [270]:
ds.columns

Index(['Timestamp', 'FRUITS_VEGGIES', 'DAILY_STRESS', 'PLACES_VISITED',
       'CORE_CIRCLE', 'SUPPORTING_OTHERS', 'SOCIAL_NETWORK', 'ACHIEVEMENT',
       'DONATION', 'BMI_RANGE', 'TODO_COMPLETED', 'FLOW', 'DAILY_STEPS',
       'LIVE_VISION', 'SLEEP_HOURS', 'LOST_VACATION', 'DAILY_SHOUTING',
       'SUFFICIENT_INCOME', 'PERSONAL_AWARDS', 'TIME_FOR_PASSION',
       'WEEKLY_MEDITATION', 'AGE', 'GENDER', 'WORK_LIFE_BALANCE_SCORE'],
      dtype='object')

In [271]:
ds=ds.iloc[:,1:]
ds.head()

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,3,0,2,5,0,5,2,0,1,6,...,7,5,5,1,4,0,5,36 to 50,Female,609.5
1,2,0,4,3,8,10,5,2,2,5,...,8,2,2,2,3,2,6,36 to 50,Female,655.6
2,2,0,3,4,4,10,3,2,2,2,...,8,10,2,2,4,8,3,36 to 50,Female,631.6
3,3,0,10,3,10,7,2,5,2,3,...,5,7,5,1,5,2,0,51 or more,Female,622.7
4,5,0,3,3,10,4,2,4,2,5,...,7,0,0,2,8,1,5,51 or more,Female,663.9

In [272]:
target_value = 0
r = ds.apply(lambda col: col[col == target_value].count())

print(r)

FRUITS_VEGGIES               552
DAILY_STRESS               15971
PLACES_VISITED              1016
CORE_CIRCLE                  312
SUPPORTING_OTHERS            740
SOCIAL_NETWORK               116
ACHIEVEMENT                 1302
DONATION                    2500
BMI_RANGE                      0
TODO_COMPLETED               540
FLOW                        1330
DAILY_STEPS                    0
LIVE_VISION                 2518
SLEEP_HOURS                    0
LOST_VACATION               8115
DAILY_SHOUTING              2430
SUFFICIENT_INCOME              0
PERSONAL_AWARDS              545
TIME_FOR_PASSION            1797
WEEKLY_MEDITATION            297
AGE                            0
GENDER                         0
WORK_LIFE_BALANCE_SCORE        0
dtype: int64

In [273]:

# Function to replace target_value with column mean
def replace_with_mean(col):
    col_mean = col.mean()
    col[col == target_value] = col_mean
    return col

# Apply the custom function to each column
ds.iloc[:,:-3]= ds.iloc[:,:-3].apply(replace_with_mean)

print(ds)

       FRUITS_VEGGIES  DAILY_STRESS  PLACES_VISITED  CORE_CIRCLE  \
0                 3.0  86408.879539         2.00000          5.0
1                 2.0  86408.879539         4.00000          3.0
2                 2.0  86408.879539         3.00000          4.0
3                 3.0  86408.879539        10.00000          3.0
4                 5.0  86408.879539         3.00000          3.0
...               ...           ...             ...          ...
15967             3.0  86408.879539         5.23297          4.0
15968             3.0  86408.879539         6.00000          8.0
15969             4.0  86408.879539         5.23297         10.0
15970             1.0  86408.879539        10.00000          8.0
15971             5.0  86408.879539         5.23297          2.0

       SUPPORTING_OTHERS  SOCIAL_NETWORK  ACHIEVEMENT  DONATION  BMI_RANGE  \
0               5.616454             5.0     2.000000  2.715314          1
1               8.000000            10.0     5.000000  2.000000          2
2               4.000000            10.0     3.000000  2.000000          2
3              10.000000             7.0     2.000000  5.000000          2
4              10.000000             4.0     2.000000  4.000000          2
...                  ...             ...          ...       ...        ...
15967           5.616454            10.0     4.000751  4.000000          2
15968           7.000000             4.0     6.000000  3.000000          1
15969          10.000000             8.0     6.000000  5.000000          1
15970           2.000000             7.0     3.000000  2.000000          1
15971          10.000000            10.0     5.000000  1.000000          2

       TODO_COMPLETED  ...  SLEEP_HOURS  LOST_VACATION  DAILY_SHOUTING  \
0                 6.0  ...            7       5.000000        5.000000
1                 5.0  ...            8       2.000000        2.000000
2                 2.0  ...            8      10.000000        2.000000
3                 3.0  ...            5       7.000000        5.000000
4                 5.0  ...            7       2.898886        2.930879
...               ...  ...          ...            ...             ...
15967             8.0  ...            7       2.898886        1.000000
15968             7.0  ...            6       2.898886        2.930879
15969             7.0  ...            7       2.898886        1.000000
15970             6.0  ...            8       7.000000        2.000000
15971             7.0  ...            8       5.000000        2.000000

       SUFFICIENT_INCOME  PERSONAL_AWARDS  TIME_FOR_PASSION  \
0                      1              4.0          3.326572
1                      2              3.0          2.000000
2                      2              4.0          8.000000
3                      1              5.0          2.000000
4                      2              8.0          1.000000
...                  ...              ...               ...
15967                  1              5.0          2.000000
15968                  2             10.0          5.000000
15969                  2             10.0          1.000000
15970                  2              1.0          6.000000
15971                  2              1.0          8.000000

       WEEKLY_MEDITATION         AGE  GENDER  WORK_LIFE_BALANCE_SCORE
0               5.000000    36 to 50  Female                    609.5
1               6.000000    36 to 50  Female                    655.6
2               3.000000    36 to 50  Female                    631.6
3               6.233346  51 or more  Female                    622.7
4               5.000000  51 or more  Female                    663.9
...                  ...         ...     ...                      ...
15967           5.000000  51 or more  Female                    644.5
15968           8.000000    21 to 35  Female                    714.9
15969          10.000000    21 to 35    Male                    716.6
15970           8.000000    21 to 35  Female                    682.0
15971           4.000000    21 to 35  Female                    651.4

[15972 rows x 23 columns]

In [274]:
ds.head(20)

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,3.0,86408.879539,2.00000,5.0,5.616454,5.0,2.000000,2.715314,1,6.0,...,7,5.000000,5.000000,1,4.0,3.326572,5.000000,36 to 50,Female,609.5
1,2.0,86408.879539,4.00000,3.0,8.000000,10.0,5.000000,2.000000,2,5.0,...,8,2.000000,2.000000,2,3.0,2.000000,6.000000,36 to 50,Female,655.6
2,2.0,86408.879539,3.00000,4.0,4.000000,10.0,3.000000,2.000000,2,2.0,...,8,10.000000,2.000000,2,4.0,8.000000,3.000000,36 to 50,Female,631.6
3,3.0,86408.879539,10.00000,3.0,10.000000,7.0,2.000000,5.000000,2,3.0,...,5,7.000000,5.000000,1,5.0,2.000000,6.233346,51 or more,Female,622.7
4,5.0,86408.879539,3.00000,3.0,10.000000,4.0,2.000000,4.000000,2,5.0,...,7,2.898886,2.930879,2,8.0,1.000000,5.000000,51 or more,Female,663.9
5,3.0,86408.879539,3.00000,9.0,10.000000,10.0,2.000000,3.000000,1,6.0,...,8,2.898886,2.000000,2,10.0,8.000000,3.000000,51 or more,Female,722.3
6,4.0,86408.879539,10.00000,6.0,10.000000,10.0,3.000000,5.000000,2,8.0,...,7,10.000000,2.930879,2,10.0,8.000000,10.000000,51 or more,Male,727.2
7,3.0,86408.879539,5.00000,3.0,5.000000,7.0,4.000000,2.715314,1,8.0,...,6,2.898886,2.000000,2,8.0,2.000000,2.000000,21 to 35,Female,676.2
8,5.0,86408.879539,6.00000,4.0,3.000000,3.0,5.000000,4.000000,1,10.0,...,10,2.898886,2.000000,2,10.0,3.000000,10.000000,21 to 35,Female,702.8
9,4.0,86408.879539,2.00000,6.0,10.000000,10.0,4.000751,4.000000,2,3.0,...,6,2.898886,2.930879,1,3.0,8.000000,1.000000,51 or more,Female,634.4
10,2.0,86408.879539,7.00000,7.0,1.000000,1.0,3.000000,2.715314,2,2.0,...,8,7.000000,3.000000,2,3.0,3.326572,6.000000,36 to 50,Female,610.1
11,1.0,86408.879539,3.00000,8.0,5.616454,2.0,1.000000,2.715314,1,2.0,...,7,7.000000,1.000000,2,4.0,1.000000,7.000000,21 to 35,Male,618.6
12,2.0,86408.879539,10.00000,5.0,2.000000,8.0,3.000000,4.000000,2,7.0,...,8,2.898886,2.930879,2,5.0,2.000000,7.000000,21 to 35,Male,686.4
13,5.0,86408.879539,5.23297,3.0,6.000000,6.0,6.000000,3.000000,1,8.0,...,6,2.898886,3.000000,2,5.0,6.000000,5.000000,36 to 50,Female,689.6
14,3.0,86408.879539,2.00000,3.0,7.000000,5.0,3.000000,2.000000,1,8.0,...,8,3.000000,2.000000,1,4.0,5.000000,4.000000,21 to 35,Female,639.7
15,3.0,86408.879539,5.00000,4.0,10.000000,10.0,2.000000,5.000000,1,7.0,...,6,1.000000,2.000000,2,8.0,3.000000,10.000000,51 or more,Female,720.4
16,4.0,86408.879539,10.00000,4.0,6.000000,10.0,4.000000,2.715314,1,8.0,...,8,1.000000,1.000000,2,3.0,3.000000,3.000000,21 to 35,Male,673.5
17,4.0,86408.879539,10.00000,10.0,5.000000,10.0,4.000751,1.000000,1,7.0,...,8,2.898886,3.000000,2,4.0,8.000000,6.000000,21 to 35,Male,707.6
18,5.0,86408.879539,10.00000,7.0,10.000000,5.0,6.000000,5.000000,1,6.0,...,9,2.898886,7.000000,2,5.0,4.000000,7.000000,36 to 50,Female,727.8
19,3.0,86408.879539,6.00000,10.0,10.000000,6.0,3.000000,5.000000,2,8.0,...,8,2.898886,2.930879,2,5.0,1.000000,2.000000,36 to 50,Male,687.1

In [275]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler = StandardScaler()

# Fit and transform the specific column
ds["DAILY_STRESS"] = scaler.fit_transform(ds[["DAILY_STRESS"]])

In [276]:
ds.head(20)

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,3.0,-0.007913,2.00000,5.0,5.616454,5.0,2.000000,2.715314,1,6.0,...,7,5.000000,5.000000,1,4.0,3.326572,5.000000,36 to 50,Female,609.5
1,2.0,-0.007913,4.00000,3.0,8.000000,10.0,5.000000,2.000000,2,5.0,...,8,2.000000,2.000000,2,3.0,2.000000,6.000000,36 to 50,Female,655.6
2,2.0,-0.007913,3.00000,4.0,4.000000,10.0,3.000000,2.000000,2,2.0,...,8,10.000000,2.000000,2,4.0,8.000000,3.000000,36 to 50,Female,631.6
3,3.0,-0.007913,10.00000,3.0,10.000000,7.0,2.000000,5.000000,2,3.0,...,5,7.000000,5.000000,1,5.0,2.000000,6.233346,51 or more,Female,622.7
4,5.0,-0.007913,3.00000,3.0,10.000000,4.0,2.000000,4.000000,2,5.0,...,7,2.898886,2.930879,2,8.0,1.000000,5.000000,51 or more,Female,663.9
5,3.0,-0.007913,3.00000,9.0,10.000000,10.0,2.000000,3.000000,1,6.0,...,8,2.898886,2.000000,2,10.0,8.000000,3.000000,51 or more,Female,722.3
6,4.0,-0.007913,10.00000,6.0,10.000000,10.0,3.000000,5.000000,2,8.0,...,7,10.000000,2.930879,2,10.0,8.000000,10.000000,51 or more,Male,727.2
7,3.0,-0.007913,5.00000,3.0,5.000000,7.0,4.000000,2.715314,1,8.0,...,6,2.898886,2.000000,2,8.0,2.000000,2.000000,21 to 35,Female,676.2
8,5.0,-0.007913,6.00000,4.0,3.000000,3.0,5.000000,4.000000,1,10.0,...,10,2.898886,2.000000,2,10.0,3.000000,10.000000,21 to 35,Female,702.8
9,4.0,-0.007913,2.00000,6.0,10.000000,10.0,4.000751,4.000000,2,3.0,...,6,2.898886,2.930879,1,3.0,8.000000,1.000000,51 or more,Female,634.4
10,2.0,-0.007913,7.00000,7.0,1.000000,1.0,3.000000,2.715314,2,2.0,...,8,7.000000,3.000000,2,3.0,3.326572,6.000000,36 to 50,Female,610.1
11,1.0,-0.007913,3.00000,8.0,5.616454,2.0,1.000000,2.715314,1,2.0,...,7,7.000000,1.000000,2,4.0,1.000000,7.000000,21 to 35,Male,618.6
12,2.0,-0.007913,10.00000,5.0,2.000000,8.0,3.000000,4.000000,2,7.0,...,8,2.898886,2.930879,2,5.0,2.000000,7.000000,21 to 35,Male,686.4
13,5.0,-0.007913,5.23297,3.0,6.000000,6.0,6.000000,3.000000,1,8.0,...,6,2.898886,3.000000,2,5.0,6.000000,5.000000,36 to 50,Female,689.6
14,3.0,-0.007913,2.00000,3.0,7.000000,5.0,3.000000,2.000000,1,8.0,...,8,3.000000,2.000000,1,4.0,5.000000,4.000000,21 to 35,Female,639.7
15,3.0,-0.007913,5.00000,4.0,10.000000,10.0,2.000000,5.000000,1,7.0,...,6,1.000000,2.000000,2,8.0,3.000000,10.000000,51 or more,Female,720.4
16,4.0,-0.007913,10.00000,4.0,6.000000,10.0,4.000000,2.715314,1,8.0,...,8,1.000000,1.000000,2,3.0,3.000000,3.000000,21 to 35,Male,673.5
17,4.0,-0.007913,10.00000,10.0,5.000000,10.0,4.000751,1.000000,1,7.0,...,8,2.898886,3.000000,2,4.0,8.000000,6.000000,21 to 35,Male,707.6
18,5.0,-0.007913,10.00000,7.0,10.000000,5.0,6.000000,5.000000,1,6.0,...,9,2.898886,7.000000,2,5.0,4.000000,7.000000,36 to 50,Female,727.8
19,3.0,-0.007913,6.00000,10.0,10.000000,6.0,3.000000,5.000000,2,8.0,...,8,2.898886,2.930879,2,5.0,1.000000,2.000000,36 to 50,Male,687.1

In [277]:
ds.describe()

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,DAILY_STEPS,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,WORK_LIFE_BALANCE_SCORE
count,15972.000000,1.597200e+04,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,...,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000,15972.000000
mean,3.023686,8.897355e-19,5.565846,5.615672,5.876670,6.521288,4.326883,3.140326,1.410656,5.940260,...,5.703606,4.343655,7.042888,4.371742,3.376787,1.728963,5.906449,3.700842,6.349255,666.751503
std,1.332639,1.000031e+00,3.019256,2.731892,2.996898,3.036592,2.486648,1.446933,0.491968,2.394121,...,2.891013,2.805304,1.199044,2.681947,2.378394,0.444509,2.897348,2.462486,2.892009,45.019868
min,1.000000,-7.912868e-03,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,480.000000
25%,2.000000,-7.912868e-03,3.000000,3.000000,3.000000,4.000000,2.000000,2.000000,1.000000,4.000000,...,3.000000,2.000000,6.000000,2.898886,2.000000,1.000000,4.000000,2.000000,4.000000,636.000000
50%,3.000000,-7.912868e-03,5.000000,5.000000,5.616454,6.000000,4.000000,3.000000,1.000000,6.000000,...,5.000000,3.752129,7.000000,2.898886,2.930879,2.000000,5.711558,3.000000,7.000000,667.700000
75%,4.000000,-7.912868e-03,8.000000,8.000000,10.000000,10.000000,6.000000,5.000000,2.000000,8.000000,...,8.000000,5.000000,8.000000,5.000000,4.000000,2.000000,9.000000,5.000000,10.000000,698.500000
max,5.000000,1.263764e+02,10.000000,10.000000,10.000000,10.000000,10.000000,5.000000,2.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,10.000000,10.000000,10.000000,820.200000

In [278]:
ds["DAILY_STRESS"]=ds["DAILY_STRESS"]*1000
ds.head(20)

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER,WORK_LIFE_BALANCE_SCORE
0,3.0,-7.912868,2.00000,5.0,5.616454,5.0,2.000000,2.715314,1,6.0,...,7,5.000000,5.000000,1,4.0,3.326572,5.000000,36 to 50,Female,609.5
1,2.0,-7.912868,4.00000,3.0,8.000000,10.0,5.000000,2.000000,2,5.0,...,8,2.000000,2.000000,2,3.0,2.000000,6.000000,36 to 50,Female,655.6
2,2.0,-7.912868,3.00000,4.0,4.000000,10.0,3.000000,2.000000,2,2.0,...,8,10.000000,2.000000,2,4.0,8.000000,3.000000,36 to 50,Female,631.6
3,3.0,-7.912868,10.00000,3.0,10.000000,7.0,2.000000,5.000000,2,3.0,...,5,7.000000,5.000000,1,5.0,2.000000,6.233346,51 or more,Female,622.7
4,5.0,-7.912868,3.00000,3.0,10.000000,4.0,2.000000,4.000000,2,5.0,...,7,2.898886,2.930879,2,8.0,1.000000,5.000000,51 or more,Female,663.9
5,3.0,-7.912868,3.00000,9.0,10.000000,10.0,2.000000,3.000000,1,6.0,...,8,2.898886,2.000000,2,10.0,8.000000,3.000000,51 or more,Female,722.3
6,4.0,-7.912868,10.00000,6.0,10.000000,10.0,3.000000,5.000000,2,8.0,...,7,10.000000,2.930879,2,10.0,8.000000,10.000000,51 or more,Male,727.2
7,3.0,-7.912868,5.00000,3.0,5.000000,7.0,4.000000,2.715314,1,8.0,...,6,2.898886,2.000000,2,8.0,2.000000,2.000000,21 to 35,Female,676.2
8,5.0,-7.912868,6.00000,4.0,3.000000,3.0,5.000000,4.000000,1,10.0,...,10,2.898886,2.000000,2,10.0,3.000000,10.000000,21 to 35,Female,702.8
9,4.0,-7.912868,2.00000,6.0,10.000000,10.0,4.000751,4.000000,2,3.0,...,6,2.898886,2.930879,1,3.0,8.000000,1.000000,51 or more,Female,634.4
10,2.0,-7.912868,7.00000,7.0,1.000000,1.0,3.000000,2.715314,2,2.0,...,8,7.000000,3.000000,2,3.0,3.326572,6.000000,36 to 50,Female,610.1
11,1.0,-7.912868,3.00000,8.0,5.616454,2.0,1.000000,2.715314,1,2.0,...,7,7.000000,1.000000,2,4.0,1.000000,7.000000,21 to 35,Male,618.6
12,2.0,-7.912868,10.00000,5.0,2.000000,8.0,3.000000,4.000000,2,7.0,...,8,2.898886,2.930879,2,5.0,2.000000,7.000000,21 to 35,Male,686.4
13,5.0,-7.912868,5.23297,3.0,6.000000,6.0,6.000000,3.000000,1,8.0,...,6,2.898886,3.000000,2,5.0,6.000000,5.000000,36 to 50,Female,689.6
14,3.0,-7.912868,2.00000,3.0,7.000000,5.0,3.000000,2.000000,1,8.0,...,8,3.000000,2.000000,1,4.0,5.000000,4.000000,21 to 35,Female,639.7
15,3.0,-7.912868,5.00000,4.0,10.000000,10.0,2.000000,5.000000,1,7.0,...,6,1.000000,2.000000,2,8.0,3.000000,10.000000,51 or more,Female,720.4
16,4.0,-7.912868,10.00000,4.0,6.000000,10.0,4.000000,2.715314,1,8.0,...,8,1.000000,1.000000,2,3.0,3.000000,3.000000,21 to 35,Male,673.5
17,4.0,-7.912868,10.00000,10.0,5.000000,10.0,4.000751,1.000000,1,7.0,...,8,2.898886,3.000000,2,4.0,8.000000,6.000000,21 to 35,Male,707.6
18,5.0,-7.912868,10.00000,7.0,10.000000,5.0,6.000000,5.000000,1,6.0,...,9,2.898886,7.000000,2,5.0,4.000000,7.000000,36 to 50,Female,727.8
19,3.0,-7.912868,6.00000,10.0,10.000000,6.0,3.000000,5.000000,2,8.0,...,8,2.898886,2.930879,2,5.0,1.000000,2.000000,36 to 50,Male,687.1

In [279]:
x=ds.iloc[:,:-1]
y=ds.iloc[:,-1]

x.replace({'GENDER':{'Male':0,'Female':1}} , inplace=True)

In [280]:
x["AGE"].value_counts()

21 to 35        6108
36 to 50        4655
51 or more      3390
Less than 20    1819
Name: AGE, dtype: int64

In [281]:
x.replace({'AGE':{'Less than 20':0,'51 or more':4,'21 to 35':1,'36 to 50':2}} , inplace=True)

x.head(30)

,FRUITS_VEGGIES,DAILY_STRESS,PLACES_VISITED,CORE_CIRCLE,SUPPORTING_OTHERS,SOCIAL_NETWORK,ACHIEVEMENT,DONATION,BMI_RANGE,TODO_COMPLETED,...,LIVE_VISION,SLEEP_HOURS,LOST_VACATION,DAILY_SHOUTING,SUFFICIENT_INCOME,PERSONAL_AWARDS,TIME_FOR_PASSION,WEEKLY_MEDITATION,AGE,GENDER
0,3.0,-7.912868,2.00000,5.0,5.616454,5.0,2.000000,2.715314,1,6.0,...,3.752129,7,5.000000,5.000000,1,4.0,3.326572,5.000000,2,1
1,2.0,-7.912868,4.00000,3.0,8.000000,10.0,5.000000,2.000000,2,5.0,...,5.000000,8,2.000000,2.000000,2,3.0,2.000000,6.000000,2,1
2,2.0,-7.912868,3.00000,4.0,4.000000,10.0,3.000000,2.000000,2,2.0,...,5.000000,8,10.000000,2.000000,2,4.0,8.000000,3.000000,2,1
3,3.0,-7.912868,10.00000,3.0,10.000000,7.0,2.000000,5.000000,2,3.0,...,3.752129,5,7.000000,5.000000,1,5.0,2.000000,6.233346,4,1
4,5.0,-7.912868,3.00000,3.0,10.000000,4.0,2.000000,4.000000,2,5.0,...,3.752129,7,2.898886,2.930879,2,8.0,1.000000,5.000000,4,1
5,3.0,-7.912868,3.00000,9.0,10.000000,10.0,2.000000,3.000000,1,6.0,...,10.000000,8,2.898886,2.000000,2,10.0,8.000000,3.000000,4,1
6,4.0,-7.912868,10.00000,6.0,10.000000,10.0,3.000000,5.000000,2,8.0,...,5.000000,7,10.000000,2.930879,2,10.0,8.000000,10.000000,4,0
7,3.0,-7.912868,5.00000,3.0,5.000000,7.0,4.000000,2.715314,1,8.0,...,10.000000,6,2.898886,2.000000,2,8.0,2.000000,2.000000,1,1
8,5.0,-7.912868,6.00000,4.0,3.000000,3.0,5.000000,4.000000,1,10.0,...,5.000000,10,2.898886,2.000000,2,10.0,3.000000,10.000000,1,1
9,4.0,-7.912868,2.00000,6.0,10.000000,10.0,4.000751,4.000000,2,3.0,...,3.752129,6,2.898886,2.930879,1,3.0,8.000000,1.000000,4,1
10,2.0,-7.912868,7.00000,7.0,1.000000,1.0,3.000000,2.715314,2,2.0,...,4.000000,8,7.000000,3.000000,2,3.0,3.326572,6.000000,2,1
11,1.0,-7.912868,3.00000,8.0,5.616454,2.0,1.000000,2.715314,1,2.0,...,2.000000,7,7.000000,1.000000,2,4.0,1.000000,7.000000,1,0
12,2.0,-7.912868,10.00000,5.0,2.000000,8.0,3.000000,4.000000,2,7.0,...,10.000000,8,2.898886,2.930879,2,5.0,2.000000,7.000000,1,0
13,5.0,-7.912868,5.23297,3.0,6.000000,6.0,6.000000,3.000000,1,8.0,...,2.000000,6,2.898886,3.000000,2,5.0,6.000000,5.000000,2,1
14,3.0,-7.912868,2.00000,3.0,7.000000,5.0,3.000000,2.000000,1,8.0,...,5.000000,8,3.000000,2.000000,1,4.0,5.000000,4.000000,1,1
15,3.0,-7.912868,5.00000,4.0,10.000000,10.0,2.000000,5.000000,1,7.0,...,10.000000,6,1.000000,2.000000,2,8.0,3.000000,10.000000,4,1
16,4.0,-7.912868,10.00000,4.0,6.000000,10.0,4.000000,2.715314,1,8.0,...,1.000000,8,1.000000,1.000000,2,3.0,3.000000,3.000000,1,0
17,4.0,-7.912868,10.00000,10.0,5.000000,10.0,4.000751,1.000000,1,7.0,...,2.000000,8,2.898886,3.000000,2,4.0,8.000000,6.000000,1,0
18,5.0,-7.912868,10.00000,7.0,10.000000,5.0,6.000000,5.000000,1,6.0,...,10.000000,9,2.898886,7.000000,2,5.0,4.000000,7.000000,2,1
19,3.0,-7.912868,6.00000,10.0,10.000000,6.0,3.000000,5.000000,2,8.0,...,5.000000,8,2.898886,2.930879,2,5.0,1.000000,2.000000,2,0
20,2.0,-7.912868,3.00000,8.0,6.000000,5.0,1.000000,2.000000,1,8.0,...,6.000000,4,2.898886,3.000000,2,3.0,2.000000,5.000000,1,0
21,3.0,-7.912868,5.00000,4.0,5.000000,3.0,2.000000,5.000000,2,10.0,...,3.000000,7,5.000000,7.000000,2,10.0,10.000000,10.000000,1,1
22,5.0,-7.912868,8.00000,6.0,10.000000,10.0,6.000000,4.000000,2,4.0,...,3.000000,7,1.000000,2.000000,2,10.0,6.000000,8.000000,2,0
23,2.0,-7.912868,6.00000,10.0,10.000000,10.0,10.000000,5.000000,1,10.0,...,4.000000,7,2.898886,1.000000,2,10.0,5.000000,7.000000,2,0
24,2.0,-7.912868,6.00000,10.0,5.000000,5.0,6.000000,4.000000,2,6.0,...,10.000000,6,2.898886,3.000000,2,1.0,3.000000,10.000000,2,1
25,1.0,-7.912868,1.00000,3.0,6.000000,5.0,3.000000,5.000000,1,2.0,...,1.000000,7,2.898886,6.000000,2,5.0,1.000000,1.000000,1,0
26,1.0,-7.912868,1.00000,2.0,5.000000,3.0,1.000000,5.000000,1,1.0,...,1.000000,7,2.898886,4.000000,2,2.0,1.000000,1.000000,1,0
27,2.0,-7.912868,10.00000,3.0,10.000000,7.0,8.000000,3.000000,1,6.0,...,5.000000,7,2.898886,1.000000,2,10.0,2.000000,2.000000,1,1
28,3.0,-7.912868,6.00000,4.0,7.000000,10.0,3.000000,3.000000,1,4.0,...,5.000000,6,2.898886,3.000000,1,7.0,2.000000,8.000000,2,1
29,4.0,-7.912868,10.00000,3.0,1.000000,2.0,3.000000,3.000000,1,7.0,...,1.000000,7,2.898886,3.000000,2,10.0,1.000000,7.000000,0,1

In [282]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=2)

In [283]:
from sklearn.linear_model import LinearRegression
regressorl = LinearRegression()
regressorl.fit(X_train, Y_train)

y_pred=regressorl.predict(X_test)

In [284]:
from sklearn.tree import DecisionTreeRegressor
regressordt = DecisionTreeRegressor(random_state = 0)
regressordt.fit(X_train, Y_train)
y_preddt=regressordt.predict(X_test)

In [285]:
from sklearn.svm import SVR
regressorsvm = SVR(kernel = 'rbf')
regressorsvm.fit(X_train, Y_train)
y_predsvm=regressorsvm.predict(X_test)

In [286]:
from sklearn.ensemble import RandomForestRegressor
regressorrf = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressorrf.fit(X_train, Y_train)
y_predrf=regressorrf.predict(X_test)

In [287]:
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, y_pred)
r3 = r2_score(Y_test, y_predsvm)
r4 = r2_score(Y_test, y_predrf)
r5 = r2_score(Y_test, y_preddt)


print(r2)

0.9411638797128579

In [288]:
print(r3)

0.013292208916637738

In [289]:
print(r4)

0.9003351925134138

In [290]:
print(r5)

0.7263421869725314